[window]
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
size = 12.0

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[terminal.shell]
program = "/sbin/zsh"
args = ["-l"]

[colors.primary]
background = "#1f1d2e"
